### ISSUE TITLE
Error when extracting files

### ISSUE THREAD

**Issue by dannymozzer** [SydMontague/DSCSTools#12]
Every time I go to extract one of the .mvgl files I just get a "Error: not a MDB1 file" what am I missing here? Also I was wondering how I go about extracting stuff like music and images?

Great tool by the way, I really appreciate the fact that you've taken the time to make something like this for this game :)

**Comment by SydMontague** [comment]
The error means that the input file isn't the form of archive the tool supports. That probably has one of two reasons:
1. You didn't decrypt the file first (is you're using the Steam version)
2. You tried to extract a file that uses a different format

The archives that can be extracted are DSDB, DSDBA, DSDBP, DSDBPse, DSDBS, DSDBse and DSDBSP. The others (e.g. DSDBbgm) use a different archive format we haven't been able to extract yet.

Unfortunately that includes the music. :(

**Comment by dannymozzer** [comment]
Ah, OK thank you, I think that might be why it didn't work, I was trying to extract the DSDBbgm file, thanks for the help!
