### ISSUE TITLE
Disable autoencryption depending on the console value defined in the filename, also add a parameter when compiling

### ISSUE THREAD

**Issue by IlDucci** [SydMontague/DSCSTools#15]
Having the tool automatically encrypt new files is a great feature... for PC users (and Switch maybe? I don't have that version), but I would like to request some additional features to fine-tune the experience per systems:
 - Please add a feature so the tool has to read the filename:
    - If the filename reads XXXX.steam.mvgl, (I don't know what's Switch's subextension nor if it also needs encryption), the new file should also be encrypted by default.
    - If the filename reads XXXX.orbis.mvgl or XXXX.psp2.mvgl (PS4 and PSVita respectively), the new file should not be encrypted.
    - If the filename does not have one of these subextensions, encrypt by default.
 - Also, would it be possible to add an option to the --pack feature so the file is not encrypted during packing and compression? This is an alternate way, just for future-proofing/in case these subextensions disappear, the new autoencryption behavior isn't a bother to some people.

**Comment by SydMontague** [comment]
Fixed in #19
