### ISSUE TITLE
The digidestined mod  gives an error log message

### ISSUE THREAD

**Issue by beastAJ** [SydMontague/DSCSTools#24]
hello all, i found this "join() takes exactly one argument (2 given)" when installing the digidestined mod, it doesn't happen when it attempts to register the mod, so i'm wondering what's the issue, any help would be appreciated thank you very much. [
![image](https://user-images.githubusercontent.com/117190579/199269576-38f43a6f-7c30-495a-9114-94dde2be5b48.png)
](url)

**Comment by SydMontague** [comment]
This has nothing to do with this project.

It is either related to the mod manager or more likely to the mod you're trying to install.
